"""
Django settings for application project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
import sys
import logging
from pathlib import Path
from datetime import timedelta

# 配置 PyMySQL 作为 MySQL 数据库后端
import pymysql
pymysql.install_as_MySQLdb()


class ColoredFormatter(logging.Formatter):
    """带颜色的日志格式化器"""
    
    # ANSI 颜色代码
    COLORS = {
        'DEBUG': '\033[36m',      # 青色
        'INFO': '\033[32m',       # 绿色
        'WARNING': '\033[33m',    # 黄色
        'ERROR': '\033[31m',      # 红色
        'CRITICAL': '\033[35m',   # 紫色
    }
    RESET = '\033[0m'
    BOLD = '\033[1m'
    
    def __init__(self, fmt=None, datefmt=None, use_color=True):
        super().__init__(fmt, datefmt)
        self.use_color = use_color and self._is_tty()
    
    def _is_tty(self):
        """检查是否在终端中运行"""
        try:
            return hasattr(sys.stderr, 'isatty') and sys.stderr.isatty()
        except Exception:
            return False
    
    def format(self, record):
        """格式化日志记录，添加颜色"""
        # 保存原始级别名称
        original_levelname = record.levelname
        
        if self.use_color:
            levelname = record.levelname
            color = self.COLORS.get(levelname, '')
            
            # 为日志级别添加颜色和粗体
            record.levelname = f"{self.BOLD}{color}{levelname}{self.RESET}"
        
        # 先调用父类方法格式化
        formatted = super().format(record)
        
        # 恢复原始级别名称（避免影响文件日志）
        record.levelname = original_levelname
        
        # 对于ERROR和CRITICAL，为整个格式化后的消息添加颜色高亮
        if self.use_color and original_levelname in ['ERROR', 'CRITICAL']:
            color = self.COLORS.get(original_levelname, '')
            formatted = f"{self.BOLD}{color}{formatted}{self.RESET}"
        
        return formatted

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ================================================= #
# ******************** 动态配置 ******************** #
# ================================================= #

from conf.env import *

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure--z8%exyzt7e_%i@1+#1mm=%lb5=^fx_57=1@a+_y7bg5-w%)sm"
# 初始化plugins插件路径到环境变量中
PLUGINS_PATH = os.path.join(BASE_DIR, "plugins")
sys.path.insert(0, os.path.join(PLUGINS_PATH))

[
    sys.path.insert(0, os.path.join(PLUGINS_PATH, ele))
    for ele in os.listdir(PLUGINS_PATH)
    if os.path.isdir(os.path.join(PLUGINS_PATH, ele)) and not ele.startswith("__")
]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = locals().get("DEBUG", True)
ALLOWED_HOSTS = locals().get("ALLOWED_HOSTS", ["*"])

# 列权限需要排除的App应用
COLUMN_EXCLUDE_APPS = ['channels', 'captcha'] + locals().get("COLUMN_EXCLUDE_APPS", [])

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_comment_migrate",
    "rest_framework",
    "django_filters",
    "corsheaders",  # 注册跨域app
    "drf_yasg",
    "captcha",
    "channels",
    "dvadmin.system",
    "case_management",  # 案例管理应用
    "customer_management",  # 客户管理应用（包含日程管理）
    "ai_management",  # AI管理应用
]

# Force API responses to JSON only to avoid DRF browsable API template errors.
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
    ),
    "DEFAULT_PARSER_CLASSES": (
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ),
}

MIDDLEWARE = [
    "dvadmin.utils.middleware.HealthCheckMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # 跨域中间件
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "dvadmin.utils.middleware.ApiLoggingMiddleware",
]

ROOT_URLCONF = "application.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "application.wsgi.application"

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": DATABASE_ENGINE,
        "NAME": DATABASE_NAME,
        "USER": DATABASE_USER,
        "PASSWORD": DATABASE_PASSWORD,
        "HOST": DATABASE_HOST,
        "PORT": DATABASE_PORT,
        "OPTIONS": {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            "charset": "utf8mb4",
        },
    }
}
AUTH_USER_MODEL = "system.Users"
USERNAME_FIELD = "username"

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"
# # 设置django的静态文件目录
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

MEDIA_ROOT = "media"  # 媒体文件在服务器上的物理存储目录
MEDIA_URL = "/media/"  # 媒体文件的URL访问前缀（已启用权限控制，需登录才能访问）

#添加以下代码以后就不用写{% load staticfiles %}，可以直接引用
STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder"
)
# 收集静态文件，必须将 MEDIA_ROOT,STATICFILES_DIRS先注释
# python manage.py collectstatic
# STATIC_ROOT=os.path.join(BASE_DIR,'static')

# ================================================= #
# ******************* 跨域的配置 ******************* #
# ================================================= #

# 全部允许配置
CORS_ORIGIN_ALLOW_ALL = True
# 允许cookie
CORS_ALLOW_CREDENTIALS = True  # 指明在跨域访问中，后端是否支持对cookie的操作

# 明确允许的源（开发环境）
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# 允许的请求头
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# ================================================= #
# ******************* 第三方服务配置 **************** #
# ================================================= #

# 高德地图 Web 服务 Key（用于后端逆地理编码等场景）
# 注意：请在部署环境中通过环境变量或 conf/env.py 覆盖为真实的生产 Key
AMAP_WEB_KEY = locals().get("AMAP_WEB_KEY", "692f4ac57f5700a4a212e4021ee91f96")

# 允许的请求方法
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# ===================================================== #
# ********************* channels配置 ******************* #
# ===================================================== #
ASGI_APPLICATION = 'application.asgi.application'

# Channels 配置：优先使用 REDIS_URL/REDIS_HOST，未配置则回退内存层
_use_redis = locals().get("USE_REDIS", True)
if isinstance(_use_redis, str):
    _use_redis = _use_redis.lower() == 'true'
_redis_url = (locals().get("REDIS_URL") or os.getenv("REDIS_URL") or "").strip()
_redis_host = (locals().get("REDIS_HOST") or os.getenv("REDIS_HOST") or "").strip()
_redis_password = (locals().get("REDIS_PASSWORD") or os.getenv("REDIS_PASSWORD") or "").strip()
_redis_db = int(locals().get("REDIS_DB") or os.getenv("REDIS_DB") or 0)

if _use_redis and (_redis_url or _redis_host):
    # 如果提供了 REDIS_URL，直接使用；否则从 REDIS_HOST 构建
    if _redis_url:
        host_cfg = _redis_url
    else:
        # 构建 Redis URL：有密码时使用 redis://:password@host:port/db，无密码时使用 redis://host:port/db
        if _redis_password:
            host_cfg = f"redis://:{_redis_password}@{_redis_host}:6379/{_redis_db}"
        else:
            host_cfg = f"redis://{_redis_host}:6379/{_redis_db}"
    
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [host_cfg],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }


# ================================================= #
# ********************* 日志配置 ******************* #
# ================================================= #
# # log 配置部分BEGIN #
SERVER_LOGS_FILE = os.path.join(BASE_DIR, "logs", "server.log")
ERROR_LOGS_FILE = os.path.join(BASE_DIR, "logs", "error.log")
LOGS_FILE = os.path.join(BASE_DIR, "logs")
if not os.path.exists(os.path.join(BASE_DIR, "logs")):
    os.makedirs(os.path.join(BASE_DIR, "logs"))

# 格式:[2020-04-22 23:33:01][micoservice.apps.ready():16] [INFO] 这是一条日志:
# 格式:[日期][模块.函数名称():行号] [级别] 信息
STANDARD_LOG_FORMAT = (
    "[%(asctime)s][%(name)s.%(funcName)s():%(lineno)d] [%(levelname)s] %(message)s"
)
CONSOLE_LOG_FORMAT = (
    "[%(asctime)s][%(name)s.%(funcName)s():%(lineno)d] [%(levelname)s] %(message)s"
)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {"format": STANDARD_LOG_FORMAT},
        "console": {
            "()": ColoredFormatter,
            "format": CONSOLE_LOG_FORMAT,
            "datefmt": "%Y-%m-%d %H:%M:%S",
            "use_color": True,
        },
        "file": {
            "format": CONSOLE_LOG_FORMAT,
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": SERVER_LOGS_FILE,
            "maxBytes": 1024 * 1024 * 100,  # 100 MB
            "backupCount": 5,  # 最多备份5个
            "formatter": "standard",
            "encoding": "utf-8",
        },
        "error": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": ERROR_LOGS_FILE,
            "maxBytes": 1024 * 1024 * 100,  # 100 MB
            "backupCount": 3,  # 最多备份3个
            "formatter": "standard",
            "encoding": "utf-8",
        },
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "console",
        },

    },
    "loggers": {
        "": {
            "handlers": ["console", "error", "file"],
            "level": "INFO",
        },
        "django": {
            "handlers": ["console", "error", "file"],
            "level": "INFO",
            "propagate": False,
        },
        'django.db.backends': {
            'handlers': ["console", "error", "file"],
            'propagate': False,
            'level': "INFO"
        },
        "uvicorn.error": {
            "level": "INFO",
            "handlers": ["console", "error", "file"],
        },
        "uvicorn.access": {
            "handlers": ["console", "error", "file"],
            "level": "INFO"
        },
        "case_management": {
            "handlers": ["console", "error", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "case_management.wps_callback_views": {
            "handlers": ["console", "error", "file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# ================================================= #
# *************** REST_FRAMEWORK配置 *************** #
# ================================================= #

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
    ),
    "DATETIME_FORMAT": "%Y-%m-%d %H:%M:%S",  # 日期时间格式配置
    "DATE_FORMAT": "%Y-%m-%d",
    "DEFAULT_FILTER_BACKENDS": (
        # 'django_filters.rest_framework.DjangoFilterBackend',
        "dvadmin.utils.filters.CustomDjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ),
    "DEFAULT_PAGINATION_CLASS": "dvadmin.utils.pagination.CustomPagination",  # 自定义分页
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",  # 只有经过身份认证确定用户身份才能访问
    ],
    "EXCEPTION_HANDLER": "dvadmin.utils.exception.CustomExceptionHandler",  # 自定义的异常处理
}
# ================================================= #
# ******************** 登录方式配置 ******************** #
# ================================================= #

AUTHENTICATION_BACKENDS = ["dvadmin.utils.backends.CustomBackend"]
# ================================================= #
# ****************** simplejwt配置 ***************** #
# ================================================= #
SIMPLE_JWT = {
    # token有效时长
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=1440),
    # token刷新后的有效时间
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    # 设置前缀（同时支持 Bearer 和 JWT）
    "AUTH_HEADER_TYPES": ("Bearer", "JWT"),
    "ROTATE_REFRESH_TOKENS": True,
}

# ====================================#
# ****************swagger************#
# ====================================#
SWAGGER_SETTINGS = {
    # 基础样式
    "SECURITY_DEFINITIONS": {"basic": {"type": "basic"}},
    # 如果需要登录才能够查看接口文档, 登录的链接使用restframework自带的.
    "LOGIN_URL": "apiLogin/",
    # 'LOGIN_URL': 'rest_framework:login',
    "LOGOUT_URL": "rest_framework:logout",
    # 'DOC_EXPANSION': None,
    # 'SHOW_REQUEST_HEADERS':True,
    # 'USE_SESSION_AUTH': True,
    # 'DOC_EXPANSION': 'list',
    # 接口文档中方法列表以首字母升序排列
    "APIS_SORTER": "alpha",
    # 如果支持json提交, 则接口文档中包含json输入框
    "JSON_EDITOR": True,
    # 方法列表字母排序
    "OPERATIONS_SORTER": "alpha",
    "VALIDATOR_URL": None,
    "AUTO_SCHEMA_TYPE": 2,  # 分组根据url层级分，0、1 或 2 层
    "DEFAULT_AUTO_SCHEMA_CLASS": "dvadmin.utils.swagger.CustomSwaggerAutoSchema",
}

# ================================================= #
# **************** 验证码配置  ******************* #
# ================================================= #
CAPTCHA_IMAGE_SIZE = (160, 46)  # 设置 captcha 图片大小
CAPTCHA_LENGTH = 4  # 字符个数
CAPTCHA_TIMEOUT = 1  # 超时(minutes)
CAPTCHA_OUTPUT_FORMAT = "%(image)s %(text_field)s %(hidden_field)s "
CAPTCHA_FONT_SIZE = 36  # 字体大小
CAPTCHA_FOREGROUND_COLOR = "#64DAAA"  # 前景色
CAPTCHA_BACKGROUND_COLOR = "#F5F7F4"  # 背景色
CAPTCHA_NOISE_FUNCTIONS = (
    "captcha.helpers.noise_arcs",  # 线
    # "captcha.helpers.noise_dots",  # 点
)
# CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_char_challenge' #字母验证码
CAPTCHA_CHALLENGE_FUNCT = "captcha.helpers.math_challenge"  # 加减乘除验证码

# ================================================= #
# ******************** 其他配置 ******************** #
# ================================================= #

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"
API_LOG_ENABLE = True
# API_LOG_METHODS = 'ALL' # ['POST', 'DELETE']
API_LOG_METHODS = ["POST", "UPDATE", "DELETE", "PUT"]  # ['POST', 'DELETE']
API_MODEL_MAP = {
    "/token/": "登录模块",
    "/api/login/": "登录模块",
    "/api/plugins_market/plugins/": "插件市场",
}

DJANGO_CELERY_BEAT_TZ_AWARE = False
CELERY_TIMEZONE = "Asia/Shanghai"  # celery 时区问题
# 静态页面压缩
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

ALL_MODELS_OBJECTS = []  # 所有app models 对象

# 初始化需要执行的列表，用来初始化后执行
INITIALIZE_LIST = []
INITIALIZE_RESET_LIST = []
# 表前缀
TABLE_PREFIX = locals().get('TABLE_PREFIX', "")
# 系统配置
SYSTEM_CONFIG = {}
# 字典配置
DICTIONARY_CONFIG = {}

# ================================================= #
# ******************** 缓存配置 ******************** #
# ================================================= #
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

# ================================================= #
# ******************** 插件配置 ******************** #
# ================================================= #
# 租户共享app
TENANT_SHARED_APPS = []
# 普通租户独有app
TENANT_EXCLUSIVE_APPS = []
# 插件 urlpatterns
PLUGINS_URL_PATTERNS = []
# 所有模式有的
SHARED_APPS = []
# ********** 一键导入插件配置开始 **********
# 例如:
# from dvadmin_upgrade_center.settings import *    # 升级中心
from dvadmin3_celery.settings import *            # celery 异步任务
# from dvadmin_third.settings import *            # 第三方用户管理
# from dvadmin_ak_sk.settings import *            # 秘钥管理管理
# from dvadmin_tenants.settings import *            # 租户管理
#from dvadmin_social_auth.settings import *
#from dvadmin_uniapp.settings import *
# ...
# ********** 一键导入插件配置结束 **********

# ================================================= #
# ******************** WPS配置 ******************** #
# ================================================= #
# WPS Office Web SDK配置
WPS_CONFIG = {
    # 应用ID（从WPS开放平台获取）
    'APP_ID': locals().get('WPS_APP_ID', ''),
    
    # 应用密钥（从WPS开放平台获取）
    'APP_SECRET': locals().get('WPS_APP_SECRET', ''),
    
    # WPS服务器地址（私有化部署时需要）
    'WPS_SERVER_URL': locals().get('WPS_SERVER_URL', 'https://wwo.wps.cn'),
    
    # 回调地址（会自动生成，也可以手动配置）
    'CALLBACK_URL': locals().get('WPS_CALLBACK_URL', ''),
    
    # 文档URL有效期（秒）
    'FILE_URL_EXPIRE': 7200,  # 2小时
    
    # Token有效期（秒）
    'TOKEN_EXPIRE': 7200,  # 2小时
    
    # 是否启用WPS编辑
    'WPS_ENABLED': locals().get('WPS_ENABLED', True),
    
    # 是否启用Referer防盗链验证（默认关闭，生产环境建议启用）
    'WPS_REFERER_CHECK_ENABLED': False,
    
    # 是否启用水印功能（默认关闭）
    'WPS_WATERMARK_ENABLED': False,
    
    # 水印文字内容
    'WPS_WATERMARK_TEXT': '机密文档',
    
    # 文件大小限制（字节）
    'MAX_FILE_SIZE': 50 * 1024 * 1024,  # 50MB
    
    # 版本备份保留数量
    'VERSION_BACKUP_COUNT': 5,
    
    # 是否启用版本管理
    'VERSION_MANAGEMENT_ENABLED': True,
}

# 为了兼容性，也导出单独的配置项
WPS_APP_ID = WPS_CONFIG['APP_ID']
WPS_APP_SECRET = WPS_CONFIG['APP_SECRET']
WPS_SERVER_URL = WPS_CONFIG['WPS_SERVER_URL']
WPS_CALLBACK_URL = WPS_CONFIG['CALLBACK_URL']
WPS_FILE_URL_EXPIRE = WPS_CONFIG['FILE_URL_EXPIRE']
WPS_TOKEN_EXPIRE = WPS_CONFIG['TOKEN_EXPIRE']
WPS_ENABLED = WPS_CONFIG['WPS_ENABLED']
WPS_REFERER_CHECK_ENABLED = WPS_CONFIG['WPS_REFERER_CHECK_ENABLED']
WPS_WATERMARK_ENABLED = WPS_CONFIG['WPS_WATERMARK_ENABLED']
WPS_WATERMARK_TEXT = WPS_CONFIG['WPS_WATERMARK_TEXT']
WPS_MAX_FILE_SIZE = WPS_CONFIG['MAX_FILE_SIZE']
WPS_VERSION_BACKUP_COUNT = WPS_CONFIG['VERSION_BACKUP_COUNT']
WPS_VERSION_MANAGEMENT_ENABLED = WPS_CONFIG['VERSION_MANAGEMENT_ENABLED']

# ================================================= #
# *************** 豆包语音识别配置 *************** #
# ================================================= #
DOUBAO_CONFIG = {
    # 豆包语音识别API配置（极速版）
    'APP_ID': locals().get('DOUBAO_APP_ID', ''),
    'ACCESS_KEY': locals().get('DOUBAO_ACCESS_KEY', ''),
    'RESOURCE_ID': locals().get('DOUBAO_RESOURCE_ID', 'volc.bigasr.auc_turbo'),  # 极速版资源ID
    'API_URL': 'https://openspeech.bytedance.com',
    
    # 语音识别配置（极速版限制）
    'MAX_AUDIO_SIZE': 100 * 1024 * 1024,  # 最大100MB（极速版限制，建议20MB以内）
    'SUPPORTED_FORMATS': ['wav', 'mp3', 'ogg'],  # 极速版支持的格式：WAV / MP3 / OGG OPUS
    
    # 超时配置
    'RECOGNITION_TIMEOUT': 60,  # 识别超时时间(秒)
}

# ================================================= #
# *************** 腾讯OCR配置 *************** #
# ================================================= #
TENCENT_OCR_CONFIG = {
    'SECRET_ID': locals().get('TENCENT_OCR_SECRET_ID', ''),
    'SECRET_KEY': locals().get('TENCENT_OCR_SECRET_KEY', ''),
    'REGION': locals().get('TENCENT_OCR_REGION', 'ap-beijing'),
    'USE_SYSTEM_CONFIG': True,
}
