# Generated by Django 4.2.14 on 2025-12-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlog',
            name='login_type',
            field=models.IntegerField(choices=[(1, '普通登录'), (2, '微信扫码登录'), (3, '小程序登录')], default=1, help_text='登录类型', verbose_name='登录类型'),
        ),
    ]
