# Generated by Django 4.2.14 on 2025-12-26 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_loginlog_login_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='branch_dept',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='用户所属的分所部门（用于BRANCH角色）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_users', to='system.dept', verbose_name='所属分所部门'),
        ),
        migrations.AddField(
            model_name='users',
            name='hq_dept',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='用户所属的总所部门（用于HQ角色）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hq_users', to='system.dept', verbose_name='所属总所部门'),
        ),
        migrations.AddField(
            model_name='users',
            name='org_scope',
            field=models.CharField(blank=True, choices=[('HQ', '全所'), ('BRANCH', '本所'), ('TEAM', '本团队'), ('SELF', '本人')], help_text='用户数据范围：HQ(全所)/BRANCH(本所)/TEAM(本团队)/SELF(本人)', max_length=20, null=True, verbose_name='数据范围'),
        ),
        migrations.AddField(
            model_name='users',
            name='role_level',
            field=models.CharField(blank=True, choices=[('HQ', '总所管理'), ('BRANCH', '分所管理'), ('TEAM', '团队管理'), ('SALES', '销售')], help_text='用户角色层级：HQ(总所管理)/BRANCH(分所管理)/TEAM(团队管理)/SALES(销售)', max_length=20, null=True, verbose_name='角色层级'),
        ),
        migrations.AddField(
            model_name='users',
            name='team_dept',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='用户所属的团队部门（用于TEAM角色）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_users', to='system.dept', verbose_name='所属团队部门'),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='login_type',
            field=models.IntegerField(choices=[(1, '普通登录'), (2, '微信扫码登录')], default=1, help_text='登录类型', verbose_name='登录类型'),
        ),
    ]
