# Generated by Django 4.2.14 on 2025-12-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_add_user_role_level_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='branch_dept',
        ),
        migrations.RemoveField(
            model_name='users',
            name='hq_dept',
        ),
        migrations.RemoveField(
            model_name='users',
            name='team_dept',
        ),
        migrations.AlterField(
            model_name='users',
            name='org_scope',
            field=models.CharField(blank=True, choices=[('HQ', '全所'), ('BRANCH', '本所'), ('TEAM', '本团队'), ('SELF', '本人')], help_text='数据范围：HQ(全所)/BRANCH(本所)/TEAM(本团队)/SELF(本人)', max_length=20, null=True, verbose_name='数据范围'),
        ),
        migrations.AlterField(
            model_name='users',
            name='role_level',
            field=models.CharField(blank=True, choices=[('HQ', '总所管理'), ('BRANCH', '分所管理'), ('TEAM', '团队管理'), ('SALES', '销售')], help_text='角色层级：HQ(总所管理)/BRANCH(分所管理)/TEAM(团队管理)/SALES(销售)', max_length=20, null=True, verbose_name='角色层级'),
        ),
    ]
