# Generated by Django 4.2.14 on 2026-01-06 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tab3Session',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('session_id', models.CharField(help_text='小程序端生成的会话ID（UUID）', max_length=64, unique=True, verbose_name='会话ID')),
                ('thread_id', models.CharField(help_text='XpertAI 平台的 thread_id', max_length=64, verbose_name='Xpert Thread ID')),
                ('user_id', models.IntegerField(blank=True, help_text='关联的用户ID（可选）', null=True, verbose_name='用户ID')),
                ('last_run_id', models.CharField(blank=True, help_text='最后一次运行的 executionId（用于 resume/cancel）', max_length=64, null=True, verbose_name='最后运行ID')),
                ('is_active', models.BooleanField(default=True, help_text='会话是否仍在进行中', verbose_name='是否活跃')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'Tab3会话',
                'verbose_name_plural': 'Tab3会话',
                'db_table': 'lsl_tab3_session',
                'ordering': ['-update_datetime'],
                'indexes': [models.Index(fields=['session_id'], name='lsl_tab3_se_session_0a1e37_idx'), models.Index(fields=['user_id', '-create_datetime'], name='lsl_tab3_se_user_id_715bc0_idx'), models.Index(fields=['is_active'], name='lsl_tab3_se_is_acti_ea5622_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIChatHistory',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('user_id', models.IntegerField(help_text='发起对话的用户ID', verbose_name='用户ID')),
                ('message', models.TextField(help_text='用户发送的消息内容', verbose_name='用户消息')),
                ('response', models.TextField(help_text='AI返回的响应内容', verbose_name='AI响应')),
                ('context_type', models.CharField(blank=True, help_text='关联的业务类型，如：case（案件）、customer（客户）等', max_length=50, null=True, verbose_name='上下文类型')),
                ('context_id', models.IntegerField(blank=True, help_text='关联的业务ID', null=True, verbose_name='上下文ID')),
                ('model_name', models.CharField(blank=True, help_text='本次对话使用的AI模型名称', max_length=100, null=True, verbose_name='使用的AI模型')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'AI对话历史',
                'verbose_name_plural': 'AI对话历史',
                'db_table': 'ai_chat_history',
                'ordering': ['-create_datetime'],
                'indexes': [models.Index(fields=['user_id', '-create_datetime'], name='ai_chat_his_user_id_9d31b6_idx'), models.Index(fields=['context_type', 'context_id'], name='ai_chat_his_context_a127fd_idx')],
            },
        ),
    ]
