# Generated by Django 4.2.x

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIConversation",
            fields=[
                ("id", models.BigAutoField(help_text="Id", primary_key=True, serialize=False, verbose_name="Id")),
                ("description", models.CharField(blank=True, help_text="描述", max_length=255, null=True, verbose_name="描述")),
                ("modifier", models.CharField(blank=True, help_text="修改人", max_length=255, null=True, verbose_name="修改人")),
                ("dept_belong_id", models.CharField(blank=True, help_text="数据归属部门", max_length=255, null=True, verbose_name="数据归属部门")),
                ("update_datetime", models.DateTimeField(auto_now=True, help_text="修改时间", null=True, verbose_name="修改时间")),
                ("create_datetime", models.DateTimeField(auto_now_add=True, help_text="创建时间", null=True, verbose_name="创建时间")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, help_text="是否软删除", verbose_name="是否软删除")),
                ("user_id", models.IntegerField(db_index=True, help_text="会话归属用户ID", verbose_name="用户ID")),
                ("title", models.CharField(default="新会话", help_text="会话标题", max_length=200, verbose_name="会话标题")),
                ("pinned", models.BooleanField(db_index=True, default=False, help_text="会话是否置顶", verbose_name="是否置顶")),
                ("last_message_time", models.DateTimeField(blank=True, db_index=True, help_text="最后一条消息时间", null=True, verbose_name="最后消息时间")),
                ("creator", models.ForeignKey(db_constraint=False, help_text="创建人", null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name="creator_query", to=settings.AUTH_USER_MODEL, verbose_name="创建人")),
            ],
            options={
                "verbose_name": "AI会话",
                "verbose_name_plural": "AI会话",
                "db_table": "ai_conversation",
                "ordering": ["-pinned", "-last_message_time", "-create_datetime"],
                "indexes": [
                    models.Index(fields=["user_id", "-last_message_time"], name="ai_conv_user_lastmsg_idx"),
                    models.Index(fields=["user_id", "-pinned"], name="ai_conv_user_pinned_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIMessage",
            fields=[
                ("id", models.BigAutoField(help_text="Id", primary_key=True, serialize=False, verbose_name="Id")),
                ("description", models.CharField(blank=True, help_text="描述", max_length=255, null=True, verbose_name="描述")),
                ("modifier", models.CharField(blank=True, help_text="修改人", max_length=255, null=True, verbose_name="修改人")),
                ("dept_belong_id", models.CharField(blank=True, help_text="数据归属部门", max_length=255, null=True, verbose_name="数据归属部门")),
                ("update_datetime", models.DateTimeField(auto_now=True, help_text="修改时间", null=True, verbose_name="修改时间")),
                ("create_datetime", models.DateTimeField(auto_now_add=True, help_text="创建时间", null=True, verbose_name="创建时间")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, help_text="是否软删除", verbose_name="是否软删除")),
                ("role", models.CharField(choices=[("user", "用户"), ("assistant", "助手"), ("system", "系统")], db_index=True, default="assistant", help_text="消息角色", max_length=20, verbose_name="角色")),
                ("message_type", models.CharField(choices=[("text", "文本"), ("card", "卡片"), ("action_result", "操作结果"), ("scope_hint", "范围提示"), ("error", "错误")], db_index=True, default="text", help_text="消息类型", max_length=30, verbose_name="消息类型")),
                ("content_json", models.JSONField(blank=True, default=dict, help_text="结构化消息内容", verbose_name="消息内容")),
                ("tool_trace", models.JSONField(blank=True, default=list, help_text="工具调用轨迹", verbose_name="工具轨迹")),
                ("conversation", models.ForeignKey(db_constraint=False, help_text="所属会话", on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="ai_management.aiconversation", verbose_name="会话")),
                ("creator", models.ForeignKey(db_constraint=False, help_text="创建人", null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name="creator_query", to=settings.AUTH_USER_MODEL, verbose_name="创建人")),
            ],
            options={
                "verbose_name": "AI消息",
                "verbose_name_plural": "AI消息",
                "db_table": "ai_message",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["conversation", "id"], name="ai_msg_conv_id_idx"),
                    models.Index(fields=["conversation", "message_type"], name="ai_msg_conv_type_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIPendingAction",
            fields=[
                ("id", models.BigAutoField(help_text="Id", primary_key=True, serialize=False, verbose_name="Id")),
                ("description", models.CharField(blank=True, help_text="描述", max_length=255, null=True, verbose_name="描述")),
                ("modifier", models.CharField(blank=True, help_text="修改人", max_length=255, null=True, verbose_name="修改人")),
                ("dept_belong_id", models.CharField(blank=True, help_text="数据归属部门", max_length=255, null=True, verbose_name="数据归属部门")),
                ("update_datetime", models.DateTimeField(auto_now=True, help_text="修改时间", null=True, verbose_name="修改时间")),
                ("create_datetime", models.DateTimeField(auto_now_add=True, help_text="创建时间", null=True, verbose_name="创建时间")),
                ("is_deleted", models.BooleanField(db_index=True, default=False, help_text="是否软删除", verbose_name="是否软删除")),
                ("operation_id", models.CharField(help_text="对外幂等操作ID", max_length=64, unique=True, verbose_name="操作ID")),
                ("user_id", models.IntegerField(db_index=True, help_text="动作归属用户ID", verbose_name="用户ID")),
                ("action_type", models.CharField(help_text="如 followup_create", max_length=64, verbose_name="动作类型")),
                ("risk_level", models.CharField(choices=[("low", "低风险"), ("high", "高风险")], default="low", help_text="低风险或高风险", max_length=16, verbose_name="风险等级")),
                ("entity_type", models.CharField(blank=True, help_text="如 customer/followup", max_length=64, null=True, verbose_name="实体类型")),
                ("entity_id", models.IntegerField(blank=True, help_text="关联实体ID", null=True, verbose_name="实体ID")),
                ("draft_payload", models.JSONField(blank=True, default=dict, help_text="待确认草稿内容", verbose_name="草稿负载")),
                ("status", models.CharField(choices=[("pending", "待确认"), ("cancelled", "已取消"), ("executed", "已执行"), ("expired", "已过期"), ("approval_pending", "审批中"), ("failed", "执行失败")], db_index=True, default="pending", help_text="动作状态", max_length=32, verbose_name="状态")),
                ("expire_at", models.DateTimeField(db_index=True, help_text="超过该时间不允许确认", verbose_name="过期时间")),
                ("last_idempotency_key", models.CharField(blank=True, help_text="防重复提交", max_length=128, null=True, verbose_name="最后幂等键")),
                ("result_json", models.JSONField(blank=True, default=dict, help_text="执行结果负载", verbose_name="执行结果")),
                ("conversation", models.ForeignKey(blank=True, db_constraint=False, help_text="所属会话", null=True, on_delete=django.db.models.deletion.CASCADE, related_name="pending_actions", to="ai_management.aiconversation", verbose_name="会话")),
                ("creator", models.ForeignKey(db_constraint=False, help_text="创建人", null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name="creator_query", to=settings.AUTH_USER_MODEL, verbose_name="创建人")),
            ],
            options={
                "verbose_name": "AI待确认动作",
                "verbose_name_plural": "AI待确认动作",
                "db_table": "ai_pending_action",
                "ordering": ["-create_datetime"],
                "indexes": [
                    models.Index(fields=["operation_id"], name="ai_pend_opid_idx"),
                    models.Index(fields=["user_id", "status"], name="ai_pend_user_status_idx"),
                    models.Index(fields=["conversation", "status"], name="ai_pend_conv_status_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="tab3session",
            name="conversation",
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="关联到 AIConversation", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tab3_sessions", to="ai_management.aiconversation", verbose_name="会话归属"),
        ),
        migrations.AddIndex(
            model_name="tab3session",
            index=models.Index(
                fields=["conversation", "-create_datetime"],
                name="lsl_tab3_conv_ctime_idx",
            ),
        ),
    ]
