# Generated by Django 4.2.14 on 2025-10-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('document_name', models.CharField(max_length=200, verbose_name='文档名称')),
                ('document_type', models.CharField(choices=[('word', 'Word文档'), ('pdf', 'PDF文档'), ('excel', 'Excel文档')], max_length=50, verbose_name='文档类型')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='文件路径')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='文件大小（字节）')),
                ('document_content', models.TextField(blank=True, null=True, verbose_name='文档内容')),
                ('generation_method', models.CharField(choices=[('manual', '人工录入'), ('ai', 'AI生成')], max_length=20, verbose_name='生成方式')),
                ('template_used', models.CharField(blank=True, max_length=200, null=True, verbose_name='使用的模板')),
                ('generation_params', models.JSONField(blank=True, null=True, verbose_name='生成参数')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '案例文档',
                'verbose_name_plural': '案例文档',
                'db_table': 'case_documents',
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='CaseManagement',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('case_number', models.CharField(help_text='案件编号', max_length=100, unique=True, verbose_name='案号')),
                ('case_type', models.CharField(help_text='民事纠纷、劳动争议等', max_length=50, verbose_name='案件类型')),
                ('jurisdiction', models.CharField(help_text='管辖法院', max_length=100, verbose_name='管辖')),
                ('draft_person', models.CharField(help_text='负责拟稿的律师', max_length=50, verbose_name='拟稿人')),
                ('case_name', models.CharField(help_text='案件标题', max_length=200, verbose_name='案件名称')),
                ('defendant_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='被告名称')),
                ('defendant_credit_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='被告统一社会信用代码')),
                ('defendant_address', models.TextField(blank=True, null=True, verbose_name='被告所住地')),
                ('defendant_legal_representative', models.CharField(blank=True, max_length=100, null=True, verbose_name='被告法定代表人')),
                ('plaintiff_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='原告名称')),
                ('plaintiff_credit_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='原告统一社会信用代码')),
                ('plaintiff_address', models.TextField(blank=True, null=True, verbose_name='原告所住地')),
                ('plaintiff_legal_representative', models.CharField(blank=True, max_length=100, null=True, verbose_name='原告法定代表人')),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='合同金额')),
                ('lawyer_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='律师费')),
                ('case_description', models.TextField(blank=True, null=True, verbose_name='案件描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '进行中'), ('completed', '已完成'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '案例管理',
                'verbose_name_plural': '案例管理',
                'db_table': 'case_management',
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('template_name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('template_type', models.CharField(help_text='起诉状、授权委托书等', max_length=50, verbose_name='模板类型')),
                ('file_path', models.CharField(max_length=500, verbose_name='模板文件路径')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='文件大小（字节）')),
                ('description', models.TextField(blank=True, null=True, verbose_name='模板描述')),
                ('placeholder_info', models.JSONField(blank=True, help_text='模板中所有占位符的JSON格式数据', null=True, verbose_name='占位符信息')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '文档模板',
                'verbose_name_plural': '文档模板',
                'db_table': 'document_templates',
                'ordering': ['-create_datetime'],
            },
        ),
    ]
