# Generated by Django 4.2.14 on 2025-10-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemanagement',
            name='facts_and_reasons',
            field=models.TextField(blank=True, null=True, verbose_name='事实与理由'),
        ),
        migrations.AddField(
            model_name='casemanagement',
            name='filing_date',
            field=models.DateField(blank=True, null=True, verbose_name='起诉日期'),
        ),
        migrations.AddField(
            model_name='casemanagement',
            name='litigation_request',
            field=models.TextField(blank=True, null=True, verbose_name='诉讼请求'),
        ),
        migrations.AddField(
            model_name='casemanagement',
            name='petitioner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='具状人'),
        ),
    ]
