# Generated by Django 4.2.14 on 2025-10-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0003_casemanagement_facts_and_reasons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemanagement',
            name='defendant_credit_code',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='被告统一社会信用代码'),
        ),
        migrations.AlterField(
            model_name='casemanagement',
            name='plaintiff_credit_code',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='原告统一社会信用代码'),
        ),
    ]
