# Generated by Django 4.2.14 on 2025-10-22 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case_management', '0004_alter_casemanagement_defendant_credit_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casedocument',
            options={'verbose_name': '案例文档', 'verbose_name_plural': '案例文档'},
        ),
        migrations.AlterModelOptions(
            name='casemanagement',
            options={'verbose_name': '案例管理', 'verbose_name_plural': '案例管理'},
        ),
        migrations.AlterModelOptions(
            name='documenttemplate',
            options={'verbose_name': '文档模板', 'verbose_name_plural': '文档模板'},
        ),
        migrations.RemoveField(
            model_name='casedocument',
            name='create_datetime',
        ),
        migrations.RemoveField(
            model_name='casedocument',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='casedocument',
            name='dept_belong_id',
        ),
        migrations.RemoveField(
            model_name='casedocument',
            name='description',
        ),
        migrations.RemoveField(
            model_name='casedocument',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='casedocument',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='casedocument',
            name='generation_method',
        ),
        migrations.RemoveField(
            model_name='casedocument',
            name='generation_params',
        ),
        migrations.RemoveField(
            model_name='casedocument',
            name='modifier',
        ),
        migrations.RemoveField(
            model_name='casedocument',
            name='template_used',
        ),
        migrations.RemoveField(
            model_name='casedocument',
            name='update_datetime',
        ),
        migrations.RemoveField(
            model_name='casemanagement',
            name='contract_amount',
        ),
        migrations.RemoveField(
            model_name='casemanagement',
            name='create_datetime',
        ),
        migrations.RemoveField(
            model_name='casemanagement',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='casemanagement',
            name='defendant_address',
        ),
        migrations.RemoveField(
            model_name='casemanagement',
            name='defendant_credit_code',
        ),
        migrations.RemoveField(
            model_name='casemanagement',
            name='defendant_legal_representative',
        ),
        migrations.RemoveField(
            model_name='casemanagement',
            name='defendant_name',
        ),
        migrations.RemoveField(
            model_name='casemanagement',
            name='dept_belong_id',
        ),
        migrations.RemoveField(
            model_name='casemanagement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='casemanagement',
            name='draft_person',
        ),
        migrations.RemoveField(
            model_name='casemanagement',
            name='facts_and_reasons',
        ),
        migrations.RemoveField(
            model_name='casemanagement',
            name='filing_date',
        ),
        migrations.RemoveField(
            model_name='casemanagement',
            name='jurisdiction',
        ),
        migrations.RemoveField(
            model_name='casemanagement',
            name='lawyer_fee',
        ),
        migrations.RemoveField(
            model_name='casemanagement',
            name='litigation_request',
        ),
        migrations.RemoveField(
            model_name='casemanagement',
            name='modifier',
        ),
        migrations.RemoveField(
            model_name='casemanagement',
            name='petitioner',
        ),
        migrations.RemoveField(
            model_name='casemanagement',
            name='plaintiff_address',
        ),
        migrations.RemoveField(
            model_name='casemanagement',
            name='plaintiff_credit_code',
        ),
        migrations.RemoveField(
            model_name='casemanagement',
            name='plaintiff_legal_representative',
        ),
        migrations.RemoveField(
            model_name='casemanagement',
            name='plaintiff_name',
        ),
        migrations.RemoveField(
            model_name='casemanagement',
            name='status',
        ),
        migrations.RemoveField(
            model_name='casemanagement',
            name='update_datetime',
        ),
        migrations.RemoveField(
            model_name='documenttemplate',
            name='create_datetime',
        ),
        migrations.RemoveField(
            model_name='documenttemplate',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='documenttemplate',
            name='dept_belong_id',
        ),
        migrations.RemoveField(
            model_name='documenttemplate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='documenttemplate',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='documenttemplate',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='documenttemplate',
            name='modifier',
        ),
        migrations.RemoveField(
            model_name='documenttemplate',
            name='placeholder_info',
        ),
        migrations.RemoveField(
            model_name='documenttemplate',
            name='update_datetime',
        ),
        migrations.AddField(
            model_name='casedocument',
            name='document_path',
            field=models.CharField(blank=True, help_text='文档路径', max_length=500, null=True, verbose_name='文档路径'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='document_size',
            field=models.IntegerField(default=0, help_text='文档大小(字节)', verbose_name='文档大小'),
        ),
        migrations.AddField(
            model_name='casemanagement',
            name='case_date',
            field=models.DateField(blank=True, help_text='案例日期', null=True, verbose_name='案例日期'),
        ),
        migrations.AddField(
            model_name='casemanagement',
            name='case_notes',
            field=models.TextField(blank=True, help_text='案例备注', null=True, verbose_name='案例备注'),
        ),
        migrations.AddField(
            model_name='casemanagement',
            name='case_result',
            field=models.TextField(blank=True, help_text='案例结果', null=True, verbose_name='案例结果'),
        ),
        migrations.AddField(
            model_name='casemanagement',
            name='case_status',
            field=models.CharField(default='待处理', help_text='案例状态', max_length=50, verbose_name='案例状态'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='template_content',
            field=models.TextField(default='', help_text='模板内容', verbose_name='模板内容'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='template_description',
            field=models.TextField(blank=True, help_text='模板描述', null=True, verbose_name='模板描述'),
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='case',
            field=models.ForeignKey(help_text='关联案例', on_delete=django.db.models.deletion.CASCADE, to='case_management.casemanagement', verbose_name='关联案例'),
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='document_content',
            field=models.TextField(blank=True, help_text='文档内容', null=True, verbose_name='文档内容'),
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='document_name',
            field=models.CharField(help_text='文档名称', max_length=200, verbose_name='文档名称'),
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='document_type',
            field=models.CharField(help_text='文档类型', max_length=50, verbose_name='文档类型'),
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='是否软删除', verbose_name='是否软删除'),
        ),
        migrations.AlterField(
            model_name='casemanagement',
            name='case_description',
            field=models.TextField(blank=True, help_text='案例描述', null=True, verbose_name='案例描述'),
        ),
        migrations.AlterField(
            model_name='casemanagement',
            name='case_name',
            field=models.CharField(help_text='案例名称', max_length=200, verbose_name='案例名称'),
        ),
        migrations.AlterField(
            model_name='casemanagement',
            name='case_number',
            field=models.CharField(help_text='案例编号', max_length=100, verbose_name='案例编号'),
        ),
        migrations.AlterField(
            model_name='casemanagement',
            name='case_type',
            field=models.CharField(help_text='案例类型', max_length=50, verbose_name='案例类型'),
        ),
        migrations.AlterField(
            model_name='casemanagement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='casemanagement',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='是否软删除', verbose_name='是否软删除'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否启用', verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='是否软删除', verbose_name='是否软删除'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_name',
            field=models.CharField(help_text='模板名称', max_length=200, verbose_name='模板名称'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_type',
            field=models.CharField(help_text='模板类型', max_length=50, verbose_name='模板类型'),
        ),
        migrations.AlterModelTable(
            name='casedocument',
            table='case_document',
        ),
        migrations.AlterModelTable(
            name='documenttemplate',
            table='document_template',
        ),
        migrations.CreateModel(
            name='SearchSuggestion',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('question', models.CharField(help_text='常见问题', max_length=500, verbose_name='常见问题')),
                ('category', models.CharField(default='general', help_text='问题分类', max_length=100, verbose_name='问题分类')),
                ('keywords', models.CharField(blank=True, help_text='关键词', max_length=200, null=True, verbose_name='关键词')),
                ('sort_order', models.IntegerField(default=0, help_text='排序', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用', verbose_name='是否启用')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '搜索建议',
                'verbose_name_plural': '搜索建议',
                'db_table': 'search_suggestion',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
