# Generated by Django 4.2.14 on 2025-10-22 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case_management', '0005_alter_casedocument_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulationSearchHistory',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('user_id', models.IntegerField(help_text='用户ID', verbose_name='用户ID')),
                ('search_query', models.TextField(help_text='搜索关键词', verbose_name='搜索关键词')),
                ('search_filters', models.JSONField(blank=True, help_text='搜索筛选条件', null=True, verbose_name='搜索筛选条件')),
                ('search_results_count', models.IntegerField(default=0, help_text='搜索结果数量', verbose_name='搜索结果数量')),
                ('search_time', models.FloatField(default=0.0, help_text='搜索耗时(秒)', verbose_name='搜索耗时(秒)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP地址', null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, help_text='用户代理', null=True, verbose_name='用户代理')),
                ('search_type', models.CharField(default='regulation', help_text='搜索类型', max_length=50, verbose_name='搜索类型')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '法规搜索历史',
                'verbose_name_plural': '法规搜索历史',
                'db_table': 'regulation_search_history',
                'ordering': ['-create_datetime'],
            },
        ),
    ]
