# Generated by Django 4.2.14 on 2025-10-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0006_regulationsearchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemanagement',
            name='contract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='合同金额', max_digits=20, null=True, verbose_name='合同金额'),
        ),
        migrations.AddField(
            model_name='casemanagement',
            name='defendant_address',
            field=models.CharField(blank=True, help_text='被告地址', max_length=500, null=True, verbose_name='被告地址'),
        ),
        migrations.AddField(
            model_name='casemanagement',
            name='defendant_credit_code',
            field=models.CharField(blank=True, help_text='被告统一社会信用代码', max_length=50, null=True, verbose_name='被告统一社会信用代码'),
        ),
        migrations.AddField(
            model_name='casemanagement',
            name='defendant_legal_representative',
            field=models.CharField(blank=True, help_text='被告法定代表人', max_length=100, null=True, verbose_name='被告法定代表人'),
        ),
        migrations.AddField(
            model_name='casemanagement',
            name='defendant_name',
            field=models.CharField(blank=True, help_text='被告名称', max_length=200, null=True, verbose_name='被告名称'),
        ),
        migrations.AddField(
            model_name='casemanagement',
            name='draft_person',
            field=models.CharField(blank=True, help_text='负责拟稿的律师', max_length=50, null=True, verbose_name='拟稿人'),
        ),
        migrations.AddField(
            model_name='casemanagement',
            name='facts_and_reasons',
            field=models.TextField(blank=True, help_text='事实与理由', null=True, verbose_name='事实与理由'),
        ),
        migrations.AddField(
            model_name='casemanagement',
            name='filing_date',
            field=models.DateField(blank=True, help_text='立案日期', null=True, verbose_name='立案日期'),
        ),
        migrations.AddField(
            model_name='casemanagement',
            name='jurisdiction',
            field=models.CharField(blank=True, help_text='管辖法院', max_length=200, null=True, verbose_name='管辖法院'),
        ),
        migrations.AddField(
            model_name='casemanagement',
            name='lawyer_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='律师费', max_digits=20, null=True, verbose_name='律师费'),
        ),
        migrations.AddField(
            model_name='casemanagement',
            name='litigation_request',
            field=models.TextField(blank=True, help_text='诉讼请求', null=True, verbose_name='诉讼请求'),
        ),
        migrations.AddField(
            model_name='casemanagement',
            name='petitioner',
            field=models.CharField(blank=True, help_text='申请人', max_length=100, null=True, verbose_name='申请人'),
        ),
        migrations.AddField(
            model_name='casemanagement',
            name='plaintiff_address',
            field=models.CharField(blank=True, help_text='原告地址', max_length=500, null=True, verbose_name='原告地址'),
        ),
        migrations.AddField(
            model_name='casemanagement',
            name='plaintiff_credit_code',
            field=models.CharField(blank=True, help_text='原告统一社会信用代码', max_length=50, null=True, verbose_name='原告统一社会信用代码'),
        ),
        migrations.AddField(
            model_name='casemanagement',
            name='plaintiff_legal_representative',
            field=models.CharField(blank=True, help_text='原告法定代表人', max_length=100, null=True, verbose_name='原告法定代表人'),
        ),
        migrations.AddField(
            model_name='casemanagement',
            name='plaintiff_name',
            field=models.CharField(blank=True, help_text='原告名称', max_length=200, null=True, verbose_name='原告名称'),
        ),
    ]
