# Generated by Django 4.2.14 on 2025-10-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0007_casemanagement_contract_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedocument',
            name='file_path',
            field=models.CharField(blank=True, help_text='文件路径', max_length=500, null=True, verbose_name='文件路径'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='file_size',
            field=models.IntegerField(default=0, help_text='文件大小(字节)', verbose_name='文件大小'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='generation_method',
            field=models.CharField(blank=True, help_text='生成方式', max_length=50, null=True, verbose_name='生成方式'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='template_used',
            field=models.CharField(blank=True, help_text='使用的模板', max_length=200, null=True, verbose_name='使用的模板'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='file_path',
            field=models.CharField(blank=True, help_text='文件路径', max_length=500, null=True, verbose_name='文件路径'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='file_size',
            field=models.IntegerField(default=0, help_text='文件大小(字节)', verbose_name='文件大小'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='placeholder_info',
            field=models.JSONField(blank=True, help_text='占位符信息', null=True, verbose_name='占位符信息'),
        ),
    ]
