# Generated by Django 4.2.14 on 2025-10-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0008_casedocument_file_path_casedocument_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemanagement',
            name='defendant_credit_code',
            field=models.CharField(blank=True, help_text='被告统一社会信用代码', max_length=100, null=True, verbose_name='被告统一社会信用代码'),
        ),
        migrations.AlterField(
            model_name='casemanagement',
            name='plaintiff_credit_code',
            field=models.CharField(blank=True, help_text='原告统一社会信用代码', max_length=100, null=True, verbose_name='原告统一社会信用代码'),
        ),
    ]
