# Generated by Django 4.2.14 on 2025-10-23 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case_management', '0009_alter_casemanagement_defendant_credit_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedocument',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='dept_belong_id',
            field=models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='description',
            field=models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='modifier',
            field=models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='dept_belong_id',
            field=models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='description',
            field=models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='modifier',
            field=models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='id',
            field=models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='id',
            field=models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
