# Generated by Django 4.2.14 on 2025-10-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0011_add_regulation_search_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulationsearchhistory',
            name='user_id',
            field=models.IntegerField(blank=True, help_text='用户ID', null=True, verbose_name='用户ID'),
        ),
    ]
