# Generated by Django 4.2.14 on 2025-10-28 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case_management', '0012_alter_regulationsearchhistory_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFolder',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否软删除', verbose_name='是否软删除')),
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('folder_name', models.CharField(help_text='目录名称（中文显示名）', max_length=100, verbose_name='目录名称')),
                ('folder_path', models.CharField(help_text='完整路径（英文），如：/case_documents', max_length=500, verbose_name='完整路径')),
                ('folder_type', models.CharField(choices=[('fixed', '固定目录'), ('custom', '自定义目录')], default='custom', help_text='目录类型：fixed-固定目录, custom-自定义目录', max_length=50, verbose_name='目录类型')),
                ('sort_order', models.IntegerField(default=0, help_text='排序序号', verbose_name='排序序号')),
            ],
            options={
                'verbose_name': '案件目录',
                'verbose_name_plural': '案件目录',
                'db_table': 'case_folder',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='casedocument',
            options={'ordering': ['-create_datetime'], 'verbose_name': '案例文档', 'verbose_name_plural': '案例文档'},
        ),
        migrations.AddField(
            model_name='casedocument',
            name='file_ext',
            field=models.CharField(blank=True, help_text='文件扩展名（如：.docx, .pdf）', max_length=20, null=True, verbose_name='文件扩展名'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='file_name',
            field=models.CharField(blank=True, help_text='实际文件名（含扩展名）', max_length=200, null=True, verbose_name='实际文件名'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='folder_path',
            field=models.CharField(blank=True, help_text='目录路径（冗余字段，便于查询）', max_length=500, null=True, verbose_name='目录路径'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='mime_type',
            field=models.CharField(blank=True, help_text='MIME类型', max_length=100, null=True, verbose_name='MIME类型'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='storage_type',
            field=models.CharField(choices=[('local', '本地存储'), ('oss', '阿里云OSS'), ('minio', 'MinIO')], default='local', help_text='存储类型：local-本地, oss-阿里云, minio等', max_length=20, verbose_name='存储类型'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='storage_url',
            field=models.CharField(blank=True, help_text='存储完整URL（如果使用云存储）', max_length=500, null=True, verbose_name='存储完整URL'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='template',
            field=models.ForeignKey(blank=True, help_text='关联的模板ID（如果是模板生成）', null=True, on_delete=django.db.models.deletion.SET_NULL, to='case_management.documenttemplate', verbose_name='关联模板'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='version',
            field=models.IntegerField(default=1, help_text='版本号（同一文档的不同版本）', verbose_name='版本号'),
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='case',
            field=models.ForeignKey(help_text='关联案例', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='case_management.casemanagement', verbose_name='关联案例'),
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='document_name',
            field=models.CharField(help_text='文档显示名称', max_length=200, verbose_name='文档显示名称'),
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='document_path',
            field=models.CharField(blank=True, help_text='文档路径(旧)', max_length=500, null=True, verbose_name='文档路径(旧)'),
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='document_size',
            field=models.IntegerField(default=0, help_text='文档大小(旧)', verbose_name='文档大小(旧)'),
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='document_type',
            field=models.CharField(choices=[('template', '模板生成'), ('upload', '用户上传'), ('ai', 'AI生成'), ('parse', '解析源文件')], help_text='文档类型：template-模板生成, upload-上传, ai-AI生成, parse-解析源文件', max_length=50, verbose_name='文档类型'),
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='file_path',
            field=models.CharField(blank=True, help_text='文件存储相对路径', max_length=500, null=True, verbose_name='文件存储相对路径'),
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='文件大小（字节）', null=True, verbose_name='文件大小(字节)'),
        ),
        migrations.AddIndex(
            model_name='casedocument',
            index=models.Index(fields=['case', 'folder_path'], name='case_docume_case_id_a7d2f5_idx'),
        ),
        migrations.AddIndex(
            model_name='casedocument',
            index=models.Index(fields=['template'], name='case_docume_templat_aec995_idx'),
        ),
        migrations.AddIndex(
            model_name='casedocument',
            index=models.Index(fields=['document_type'], name='case_docume_documen_131a8e_idx'),
        ),
        migrations.AddField(
            model_name='casefolder',
            name='case',
            field=models.ForeignKey(help_text='关联案件', on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='case_management.casemanagement', verbose_name='关联案件'),
        ),
        migrations.AddField(
            model_name='casefolder',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='casefolder',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='父目录ID，NULL表示根目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='case_management.casefolder', verbose_name='父目录'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='所属目录ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='case_management.casefolder', verbose_name='所属目录'),
        ),
        migrations.AddIndex(
            model_name='casefolder',
            index=models.Index(fields=['case', 'folder_path'], name='case_folder_case_id_801af7_idx'),
        ),
        migrations.AddIndex(
            model_name='casefolder',
            index=models.Index(fields=['parent'], name='case_folder_parent__a77898_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='casefolder',
            unique_together={('case', 'folder_path', 'is_deleted')},
        ),
    ]
