# Generated by Django 4.2.14 on 2025-11-04 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case_management', '0015_add_case_document_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedocument',
            name='last_edit_time',
            field=models.DateTimeField(blank=True, help_text='最后编辑时间', null=True, verbose_name='最后编辑时间'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='last_editor_id',
            field=models.BigIntegerField(blank=True, help_text='最后编辑人ID', null=True, verbose_name='最后编辑人ID'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='wps_edit_token',
            field=models.CharField(blank=True, help_text='WPS编辑令牌', max_length=500, null=True, verbose_name='WPS编辑令牌'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='wps_edit_url',
            field=models.CharField(blank=True, help_text='WPS编辑URL', max_length=500, null=True, verbose_name='WPS编辑URL'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='wps_enabled',
            field=models.BooleanField(default=True, help_text='是否启用WPS编辑', verbose_name='是否启用WPS编辑'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='wps_file_id',
            field=models.CharField(blank=True, help_text='WPS文件ID', max_length=100, null=True, verbose_name='WPS文件ID'),
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='print_count',
            field=models.IntegerField(default=1, help_text='该文档的默认打印份数（从模板继承）', verbose_name='默认打印份数'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='file_path',
            field=models.CharField(blank=True, help_text='文件路径（相对于MEDIA_ROOT的相对路径）', max_length=500, null=True, verbose_name='文件路径'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='print_count',
            field=models.IntegerField(default=1, help_text='该文书默认需要打印的份数（如3份、5份等）', verbose_name='默认打印份数'),
        ),
        migrations.CreateModel(
            name='WPSEditRecord',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('user_id', models.BigIntegerField(help_text='用户ID', verbose_name='用户ID')),
                ('user_name', models.CharField(blank=True, help_text='用户名', max_length=100, null=True, verbose_name='用户名')),
                ('file_id', models.CharField(blank=True, help_text='WPS文件ID', max_length=100, null=True, verbose_name='WPS文件ID')),
                ('edit_token', models.CharField(blank=True, help_text='编辑令牌', max_length=500, null=True, verbose_name='编辑令牌')),
                ('edit_mode', models.CharField(choices=[('view', '预览'), ('edit', '编辑')], default='edit', help_text='编辑模式：view-预览, edit-编辑', max_length=20, verbose_name='编辑模式')),
                ('start_time', models.DateTimeField(auto_now_add=True, help_text='开始编辑时间', verbose_name='开始编辑时间')),
                ('end_time', models.DateTimeField(blank=True, help_text='结束编辑时间', null=True, verbose_name='结束编辑时间')),
                ('save_count', models.IntegerField(default=0, help_text='保存次数', verbose_name='保存次数')),
                ('status', models.CharField(choices=[('editing', '编辑中'), ('completed', '已完成'), ('cancelled', '已取消')], default='editing', help_text='状态：editing-编辑中, completed-已完成, cancelled-已取消', max_length=20, verbose_name='状态')),
                ('ip_address', models.CharField(blank=True, help_text='IP地址', max_length=50, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, help_text='用户代理', max_length=500, null=True, verbose_name='用户代理')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('document', models.ForeignKey(help_text='关联文档', on_delete=django.db.models.deletion.CASCADE, related_name='wps_edit_records', to='case_management.casedocument', verbose_name='文档')),
            ],
            options={
                'verbose_name': 'WPS编辑记录',
                'verbose_name_plural': 'WPS编辑记录',
                'db_table': 'wps_edit_record',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['document', 'status'], name='wps_edit_re_documen_a90dbf_idx'), models.Index(fields=['user_id'], name='wps_edit_re_user_id_6f750c_idx'), models.Index(fields=['start_time'], name='wps_edit_re_start_t_63fdc0_idx')],
            },
        ),
        migrations.CreateModel(
            name='WPSCallbackLog',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('file_id', models.CharField(blank=True, help_text='WPS文件ID', max_length=100, null=True, verbose_name='WPS文件ID')),
                ('event_type', models.CharField(help_text='事件类型', max_length=50, verbose_name='事件类型')),
                ('event_data', models.JSONField(blank=True, help_text='事件数据', null=True, verbose_name='事件数据')),
                ('callback_data', models.TextField(blank=True, help_text='回调原始数据', null=True, verbose_name='回调原始数据')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], default='success', help_text='处理状态：success-成功, failed-失败', max_length=20, verbose_name='处理状态')),
                ('error_message', models.TextField(blank=True, help_text='错误信息', null=True, verbose_name='错误信息')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('document', models.ForeignKey(blank=True, help_text='关联文档', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wps_callback_logs', to='case_management.casedocument', verbose_name='文档')),
            ],
            options={
                'verbose_name': 'WPS回调日志',
                'verbose_name_plural': 'WPS回调日志',
                'db_table': 'wps_callback_log',
                'ordering': ['-create_datetime'],
                'indexes': [models.Index(fields=['document'], name='wps_callbac_documen_ad51ed_idx'), models.Index(fields=['event_type'], name='wps_callbac_event_t_1565cb_idx'), models.Index(fields=['create_datetime'], name='wps_callbac_create__9acbe3_idx')],
            },
        ),
    ]
