# Generated by Django 4.2.14 on 2025-10-31 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case_management', '0015_add_case_document_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulationConversation',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('user_id', models.IntegerField(blank=True, default=0, help_text='用户ID', null=True, verbose_name='用户ID')),
                ('title', models.CharField(default='新对话', help_text='对话标题', max_length=200, verbose_name='对话标题')),
                ('message_count', models.IntegerField(default=0, help_text='消息数量', verbose_name='消息数量')),
                ('last_message_time', models.DateTimeField(blank=True, help_text='最后消息时间', null=True, verbose_name='最后消息时间')),
                ('is_pinned', models.BooleanField(default=False, help_text='是否置顶', verbose_name='是否置顶')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP地址', null=True, verbose_name='IP地址')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '法规检索对话',
                'verbose_name_plural': '法规检索对话',
                'db_table': 'regulation_conversation',
                'ordering': ['-is_pinned', '-last_message_time', '-create_datetime'],
            },
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='print_count',
            field=models.IntegerField(default=1, help_text='该文档的默认打印份数（从模板继承）', verbose_name='默认打印份数'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='file_path',
            field=models.CharField(blank=True, help_text='文件路径（相对于MEDIA_ROOT的相对路径）', max_length=500, null=True, verbose_name='文件路径'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='print_count',
            field=models.IntegerField(default=1, help_text='该文书默认需要打印的份数（如3份、5份等）', verbose_name='默认打印份数'),
        ),
        migrations.CreateModel(
            name='RegulationMessage',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', 'AI助手')], help_text='消息角色(user/assistant)', max_length=20, verbose_name='角色')),
                ('content', models.TextField(help_text='消息内容', verbose_name='消息内容')),
                ('query', models.TextField(blank=True, help_text='用户查询内容', null=True, verbose_name='查询内容')),
                ('filters', models.JSONField(blank=True, help_text='筛选条件', null=True, verbose_name='筛选条件')),
                ('response_time', models.FloatField(blank=True, help_text='AI响应时间', null=True, verbose_name='响应时间(秒)')),
                ('conversation', models.ForeignKey(help_text='所属对话会话', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='case_management.regulationconversation', verbose_name='对话会话')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '法规检索消息',
                'verbose_name_plural': '法规检索消息',
                'db_table': 'regulation_message',
                'ordering': ['create_datetime'],
            },
        ),
    ]
