# Generated by Django 4.2.14 on 2025-11-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0017_fix_utf8mb4_charset'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulationconversation',
            name='category',
            field=models.CharField(blank=True, default='question', help_text='问题分类(question/similar-case/regulation)', max_length=50, null=True, verbose_name='问题分类'),
        ),
    ]
