# Generated by Django 4.2.14 on 2025-11-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0018_regulationconversation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulationmessage',
            name='related_regulations',
            field=models.JSONField(blank=True, help_text='相关法规列表', null=True, verbose_name='相关法规'),
        ),
    ]
