# Generated by Django 4.2.14 on 2025-11-08 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0017_add_is_selected_to_case_document'),
        ('case_management', '0019_regulationmessage_related_regulations'),
    ]

    operations = [
    ]
