# Generated by Codex on 2026-01-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_management", "0021_add_case_relations"),
    ]

    operations = [
        migrations.AddField(
            model_name="casemanagement",
            name="status",
            field=models.CharField(
                max_length=20,
                choices=[
                    ("PUBLIC_POOL", "公海"),
                    ("FOLLOW_UP", "跟进"),
                    ("CASE", "交案"),
                    ("PAYMENT", "回款"),
                    ("WON", "赢单"),
                ],
                default="FOLLOW_UP",
                db_index=True,
                verbose_name="生命周期状态",
            ),
        ),
        migrations.AddField(
            model_name="casemanagement",
            name="sales_stage",
            field=models.CharField(
                max_length=20,
                choices=[
                    ("PUBLIC_POOL", "公海"),
                    ("BLANK", "跟进-空白"),
                    ("MEETING", "跟进-面谈"),
                    ("CASE", "交案"),
                    ("PAYMENT", "回款"),
                    ("WON", "赢单"),
                ],
                default="BLANK",
                db_index=True,
                verbose_name="展业状态",
            ),
        ),
    ]
