# Generated by Codex on 2026-01-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_management", "0022_add_case_status_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="casemanagement",
            name="create_datetime",
            field=models.DateTimeField(
                auto_now_add=True,
                null=True,
                blank=True,
                help_text="创建时间",
                verbose_name="创建时间",
            ),
        ),
        migrations.AddField(
            model_name="casemanagement",
            name="update_datetime",
            field=models.DateTimeField(
                auto_now=True,
                null=True,
                blank=True,
                help_text="更新时间",
                verbose_name="更新时间",
            ),
        ),
    ]
