# Generated by Django 4.2.14 on 2026-01-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0023_add_case_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casemanagement',
            name='sales_stage',
            field=models.CharField(choices=[('PUBLIC_POOL', '公海'), ('BLANK', '跟进-空白'), ('MEETING', '跟进-面谈'), ('CASE', '交案'), ('PAYMENT', '回款'), ('WON', '赢单')], db_index=True, default='BLANK', max_length=20, verbose_name='销售阶段'),
        ),
        migrations.AlterField(
            model_name='casemanagement',
            name='status',
            field=models.CharField(choices=[('PUBLIC_POOL', '公海'), ('FOLLOW_UP', '跟进'), ('CASE', '交案'), ('PAYMENT', '回款'), ('WON', '赢单')], db_index=True, default='FOLLOW_UP', max_length=20, verbose_name='案件状态'),
        ),
    ]
