# Generated by Django 4.2.14 on 2026-02-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_management", "0026_add_case_handler_core_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="casemanagement",
            options={"ordering": ["-create_datetime"], "verbose_name": "案例管理", "verbose_name_plural": "案例管理"},
        ),
        migrations.AlterField(
            model_name="casehandler",
            name="create_datetime",
            field=models.DateTimeField(auto_now_add=True, help_text="创建时间", null=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="casehandler",
            name="id",
            field=models.BigAutoField(help_text="Id", primary_key=True, serialize=False, verbose_name="Id"),
        ),
        migrations.AlterField(
            model_name="casehandler",
            name="update_datetime",
            field=models.DateTimeField(auto_now=True, help_text="修改时间", null=True, verbose_name="修改时间"),
        ),
    ]
