# Generated by Django 4.2.14 on 2025-12-23 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否软删除', verbose_name='是否软删除')),
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(help_text='客户名称', max_length=200, verbose_name='客户名称')),
                ('contact_person', models.CharField(blank=True, help_text='联系人', max_length=100, null=True, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, help_text='联系电话', max_length=50, null=True, verbose_name='联系电话')),
                ('contact_email', models.CharField(blank=True, help_text='联系邮箱', max_length=200, null=True, verbose_name='联系邮箱')),
                ('address', models.CharField(blank=True, help_text='地址', max_length=500, null=True, verbose_name='地址')),
                ('credit_code', models.CharField(blank=True, help_text='统一社会信用代码', max_length=100, null=True, verbose_name='统一社会信用代码')),
                ('remark', models.TextField(blank=True, help_text='备注', null=True, verbose_name='备注')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'db_table': 'customer',
                'ordering': ['-id'],
            },
        ),
    ]
