# Generated by Django 4.2.14 on 2025-12-29 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_management', '0002_add_report_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='是否软删除', verbose_name='是否软删除')),
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('title', models.CharField(help_text='日程标题', max_length=200, verbose_name='日程标题')),
                ('description', models.TextField(blank=True, help_text='日程描述', null=True, verbose_name='日程描述')),
                ('schedule_type', models.CharField(choices=[('meeting', '会议'), ('court', '开庭'), ('deadline', '截止日期'), ('reminder', '提醒'), ('other', '其他')], help_text='日程类型：meeting(会议)、court(开庭)、deadline(截止日期)、reminder(提醒)、other(其他)', max_length=50, verbose_name='日程类型')),
                ('start_time', models.DateTimeField(db_index=True, help_text='开始时间', verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, help_text='结束时间', null=True, verbose_name='结束时间')),
                ('is_all_day', models.BooleanField(default=False, help_text='是否全天事件', verbose_name='是否全天事件')),
                ('location', models.CharField(blank=True, help_text='地点', max_length=500, null=True, verbose_name='地点')),
                ('participants', models.JSONField(blank=True, default=list, help_text='参与人员（JSON格式存储）', null=True, verbose_name='参与人员')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], db_index=True, default='pending', help_text='状态：pending(待处理)、in_progress(进行中)、completed(已完成)、cancelled(已取消)', max_length=20, verbose_name='状态')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], db_index=True, default='medium', help_text='优先级：low(低)、medium(中)、high(高)、urgent(紧急)', max_length=20, verbose_name='优先级')),
                ('reminder_enabled', models.BooleanField(default=True, help_text='是否启用提醒', verbose_name='是否启用提醒')),
                ('reminder_time', models.IntegerField(blank=True, default=30, help_text='提前提醒时间（分钟）', null=True, verbose_name='提前提醒时间（分钟）')),
                ('reminder_method', models.CharField(blank=True, default='system', help_text='提醒方式：system(系统通知)、email(邮件)、sms(短信)、wechat(微信)，支持多选用逗号分隔', max_length=100, null=True, verbose_name='提醒方式')),
                ('related_type', models.CharField(blank=True, choices=[('case', '案件'), ('customer', '客户'), ('customer_plan', '客户计划'), ('visit', '拜访记录')], db_index=True, help_text='关联类型：case(案件)、customer(客户)、customer_plan(客户计划)', max_length=50, null=True, verbose_name='关联类型')),
                ('related_id', models.IntegerField(blank=True, db_index=True, help_text='关联对象ID', null=True, verbose_name='关联对象ID')),
                ('recurrence_rule', models.JSONField(blank=True, help_text='重复规则（JSON格式，支持按日/周/月/年重复）', null=True, verbose_name='重复规则')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='附件列表（JSON格式存储）', null=True, verbose_name='附件列表')),
                ('remark', models.TextField(blank=True, help_text='备注', null=True, verbose_name='备注')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '日程',
                'verbose_name_plural': '日程',
                'db_table': 'schedule',
                'ordering': ['-start_time', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleReminder',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('remind_time', models.DateTimeField(db_index=True, help_text='提醒时间', verbose_name='提醒时间')),
                ('remind_method', models.CharField(choices=[('system', '系统通知'), ('email', '邮件'), ('sms', '短信'), ('wechat', '微信')], help_text='提醒方式：system(系统通知)、email(邮件)、sms(短信)、wechat(微信)', max_length=50, verbose_name='提醒方式')),
                ('is_sent', models.BooleanField(db_index=True, default=False, help_text='是否已发送', verbose_name='是否已发送')),
                ('sent_time', models.DateTimeField(blank=True, help_text='发送时间', null=True, verbose_name='发送时间')),
                ('send_result', models.TextField(blank=True, help_text='发送结果', null=True, verbose_name='发送结果')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('schedule', models.ForeignKey(help_text='关联的日程', on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='customer_management.schedule', verbose_name='关联的日程')),
            ],
            options={
                'verbose_name': '日程提醒记录',
                'verbose_name_plural': '日程提醒记录',
                'db_table': 'schedule_reminder',
                'ordering': ['-remind_time'],
                'indexes': [models.Index(fields=['schedule', 'is_sent'], name='schedule_re_schedul_005c77_idx'), models.Index(fields=['remind_time', 'is_sent'], name='schedule_re_remind__2520c8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['start_time', 'status'], name='schedule_start_t_46a2a2_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['related_type', 'related_id'], name='schedule_related_ea767a_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['creator', 'start_time'], name='schedule_creator_273588_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['schedule_type', 'status'], name='schedule_schedul_2dd8f7_idx'),
        ),
    ]
