# Generated by Django 4.2.14 on 2025-12-30 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_management', '0005_add_organization_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('approver_role', models.CharField(blank=True, max_length=32, null=True, verbose_name='审批角色')),
                ('action', models.CharField(choices=[('approve', '通过'), ('reject', '驳回')], max_length=16, verbose_name='审批动作')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='审批意见')),
                ('approval_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='审批时间')),
            ],
            options={
                'verbose_name': '审批历史',
                'verbose_name_plural': '审批历史',
                'db_table': 'customer_approval_history',
            },
        ),
        migrations.CreateModel(
            name='ApprovalTask',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('approval_type', models.CharField(choices=[('LEAD_CLAIM', '申领线索'), ('LEAD_CREATE', '新增线索'), ('HANDOVER', '客户转交')], max_length=32, verbose_name='审批类型')),
                ('approval_chain', models.JSONField(default=list, help_text='按角色顺序排列的审批链', verbose_name='审批链')),
                ('current_step', models.IntegerField(default=0, verbose_name='当前审批步骤')),
                ('current_approver_role', models.CharField(blank=True, max_length=32, null=True, verbose_name='当前审批角色')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=16, verbose_name='审批状态')),
                ('related_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='关联数据')),
                ('reject_reason', models.TextField(blank=True, null=True, verbose_name='驳回原因')),
            ],
            options={
                'verbose_name': '审批任务',
                'verbose_name_plural': '审批任务',
                'db_table': 'customer_approval_task',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('contract_no', models.CharField(max_length=64, verbose_name='合同编号')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='合同金额')),
                ('term', models.CharField(blank=True, max_length=64, null=True, verbose_name='合同期限')),
                ('service_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='服务类型')),
                ('client_subject', models.CharField(blank=True, max_length=128, null=True, verbose_name='客户主体')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认')], default='pending', max_length=16, verbose_name='合同状态')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('attachments', models.JSONField(blank=True, default=list, null=True, verbose_name='附件')),
            ],
            options={
                'verbose_name': '客户合同',
                'verbose_name_plural': '客户合同',
                'db_table': 'customer_contract',
            },
        ),
        migrations.CreateModel(
            name='LegalFee',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('pay_time', models.DateTimeField(verbose_name='支付时间')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='支付金额')),
                ('voucher_attachments', models.JSONField(blank=True, default=list, null=True, verbose_name='凭证附件')),
            ],
            options={
                'verbose_name': '律师费用',
                'verbose_name_plural': '律师费用',
                'db_table': 'customer_legal_fee',
            },
        ),
        migrations.CreateModel(
            name='RecoveryPayment',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('pay_time', models.DateTimeField(verbose_name='回款时间')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='回款金额')),
                ('collection_category', models.CharField(choices=[('arbitration', '仲裁'), ('mediation', '调解'), ('litigation', '诉讼')], max_length=32, verbose_name='催收类别')),
                ('voucher_attachments', models.JSONField(blank=True, default=list, null=True, verbose_name='凭证附件')),
            ],
            options={
                'verbose_name': '回款记录',
                'verbose_name_plural': '回款记录',
                'db_table': 'customer_recovery_payment',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('title', models.CharField(help_text='报告标题', max_length=200, verbose_name='报告标题')),
                ('type', models.CharField(choices=[('weekly', '周报'), ('monthly', '月报'), ('quarterly', '季报'), ('yearly', '年报'), ('custom', '自定义')], help_text='报告类型', max_length=20, verbose_name='报告类型')),
                ('status', models.CharField(choices=[('generating', '生成中'), ('completed', '已完成'), ('failed', '生成失败')], default='completed', help_text='状态', max_length=20, verbose_name='状态')),
                ('start_date', models.DateField(help_text='开始日期', verbose_name='开始日期')),
                ('end_date', models.DateField(help_text='结束日期', verbose_name='结束日期')),
                ('content', models.JSONField(default=dict, help_text='报告内容（JSON格式）', verbose_name='报告内容')),
            ],
            options={
                'verbose_name': '报告',
                'verbose_name_plural': '报告',
                'db_table': 'report',
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='TransferLog',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('transfer_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='转交原因')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('completed', '已完成'), ('rejected', '已驳回')], default='pending', max_length=16, verbose_name='状态')),
            ],
            options={
                'verbose_name': '转交日志',
                'verbose_name_plural': '转交日志',
                'db_table': 'customer_transfer_log',
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='creator',
        ),
        migrations.RenameIndex(
            model_name='branch',
            new_name='organizatio_headqua_d51ebf_idx',
            old_name='org_branch_hq_status_idx',
        ),
        migrations.RenameIndex(
            model_name='team',
            new_name='organizatio_branch__1db7f2_idx',
            old_name='org_team_branch_status_idx',
        ),
        migrations.RenameIndex(
            model_name='visitrecord',
            new_name='visit_recor_client__3ea2cc_idx',
            old_name='visit_reco_client__a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='visitrecord',
            new_name='visit_recor_user_id_13efc4_idx',
            old_name='visit_reco_user_id_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='visitrecord',
            new_name='visit_recor_locatio_1dadaa_idx',
            old_name='visit_reco_locatio_g7h8i9_idx',
        ),
        migrations.AddField(
            model_name='customer',
            name='branch_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='分所 ID', null=True, verbose_name='分所 ID'),
        ),
        migrations.AddField(
            model_name='customer',
            name='client_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2, null=True, verbose_name='客户等级'),
        ),
        migrations.AddField(
            model_name='customer',
            name='collection_category',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='催收类别'),
        ),
        migrations.AddField(
            model_name='customer',
            name='followup_count',
            field=models.IntegerField(default=0, verbose_name='跟进次数'),
        ),
        migrations.AddField(
            model_name='customer',
            name='hq_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='总部 ID', null=True, verbose_name='总部 ID'),
        ),
        migrations.AddField(
            model_name='customer',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='customer',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='经度'),
        ),
        migrations.AddField(
            model_name='customer',
            name='location_status',
            field=models.CharField(blank=True, choices=[('success', '定位成功'), ('fail', '定位失败'), ('denied', '拒绝'), ('offline', '离线')], max_length=32, null=True, verbose_name='定位状态'),
        ),
        migrations.AddField(
            model_name='customer',
            name='owner_user',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='经办人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to=settings.AUTH_USER_MODEL, verbose_name='经办人'),
        ),
        migrations.AddField(
            model_name='customer',
            name='owner_user_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='经办人姓名'),
        ),
        migrations.AddField(
            model_name='customer',
            name='recycle_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='回收截止时间'),
        ),
        migrations.AddField(
            model_name='customer',
            name='recycle_risk_level',
            field=models.CharField(choices=[('none', '无风险'), ('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], default='none', max_length=10, verbose_name='回收风险等级'),
        ),
        migrations.AddField(
            model_name='customer',
            name='referrer',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='引荐人'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sales_stage',
            field=models.CharField(choices=[('PUBLIC_POOL', '公海'), ('BLANK', '跟进-空白'), ('MEETING', '跟进-面谈'), ('CASE', '交案'), ('PAYMENT', '回款'), ('WON', '赢单')], default='PUBLIC_POOL', max_length=20, verbose_name='展业状态'),
        ),
        migrations.AddField(
            model_name='customer',
            name='source_channel',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='来源渠道'),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('PUBLIC_POOL', '公海'), ('FOLLOW_UP', '跟进'), ('CASE', '交案'), ('PAYMENT', '回款'), ('WON', '赢单')], default='PUBLIC_POOL', max_length=20, verbose_name='生命周期状态'),
        ),
        migrations.AddField(
            model_name='customer',
            name='team_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='团队 ID', null=True, verbose_name='团队 ID'),
        ),
        migrations.AddField(
            model_name='customer',
            name='valid_visit_count',
            field=models.IntegerField(default=0, verbose_name='有效拜访次数'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AddField(
            model_name='transferlog',
            name='approval_task',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_logs', to='customer_management.approvaltask', verbose_name='审批任务'),
        ),
        migrations.AddField(
            model_name='transferlog',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='transferlog',
            name='customer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_logs', to='customer_management.customer', verbose_name='关联客户'),
        ),
        migrations.AddField(
            model_name='transferlog',
            name='from_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_from_logs', to=settings.AUTH_USER_MODEL, verbose_name='转出人'),
        ),
        migrations.AddField(
            model_name='transferlog',
            name='to_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_to_logs', to=settings.AUTH_USER_MODEL, verbose_name='转入人'),
        ),
        migrations.AddField(
            model_name='report',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='recoverypayment',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_creators', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='recoverypayment',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='recoverypayment',
            name='customer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='recovery_payments', to='customer_management.customer', verbose_name='关联客户'),
        ),
        migrations.AddField(
            model_name='legalfee',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_fee_creators', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='legalfee',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='legalfee',
            name='customer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='legal_fees', to='customer_management.customer', verbose_name='关联客户'),
        ),
        migrations.AddField(
            model_name='contract',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_contracts', to=settings.AUTH_USER_MODEL, verbose_name='确认人'),
        ),
        migrations.AddField(
            model_name='contract',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='customer_management.customer', verbose_name='关联客户'),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='applicant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='approvaltask',
            name='related_customer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='approval_tasks', to='customer_management.customer', verbose_name='关联客户'),
        ),
        migrations.AddField(
            model_name='approvalhistory',
            name='approval_task',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='customer_management.approvaltask', verbose_name='审批任务'),
        ),
        migrations.AddField(
            model_name='approvalhistory',
            name='approver',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_histories', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='approvalhistory',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
