# Generated by Django 4.2.14 on 2025-12-31 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_management', '0008_customer_plan_collection_progress'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='collectionprogress',
            new_name='customer_co_custome_878cba_idx',
            old_name='customer_c_customer_1f8b4c_idx',
        ),
        migrations.RenameIndex(
            model_name='customerplan',
            new_name='customer_pl_custome_914570_idx',
            old_name='customer_p_customer_3d1f1f_idx',
        ),
        migrations.RenameIndex(
            model_name='customerplan',
            new_name='customer_pl_status_ef0daa_idx',
            old_name='customer_p_status_8dbd3e_idx',
        ),
        migrations.AlterField(
            model_name='collectionprogress',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='collectionprogress',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='是否软删除', verbose_name='是否软删除'),
        ),
        migrations.AlterField(
            model_name='customerplan',
            name='creator',
            field=models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='customerplan',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='是否软删除', verbose_name='是否软删除'),
        ),
    ]
