# Generated by ChatGPT on 2026-01-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer_management", "0007_feedback"),
        ("customer_management", "0010_customer_grade_collection_source"),
    ]

    operations = []

