# Generated by Django 4.2.14 on 2026-01-23 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Safe version of the original 0015 migration.
    - Keeps DB state in sync without renaming legacy indexes (which may not exist in some envs).
    - Adds schedule.other_type_content and updates ReminderMessage field definitions.
    """

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customer_management", "0014_add_reminder_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="other_type_content",
            field=models.CharField(
                max_length=200,
                blank=True,
                null=True,
                verbose_name="其他类型内容",
                help_text="当日程类型为“其他”时填写具体类型内容",
            ),
        ),
        migrations.AlterField(
            model_name="remindermessage",
            name="creator",
            field=models.ForeignKey(
                db_constraint=False,
                help_text="创建人",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AlterField(
            model_name="remindermessage",
            name="id",
            field=models.BigAutoField(
                help_text="Id",
                primary_key=True,
                serialize=False,
                verbose_name="Id",
            ),
        ),
        migrations.AlterField(
            model_name="remindermessage",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="接收提醒的用户（账号）",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_reminders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="接收人",
            ),
        ),
    ]
