# Generated by Django 4.2.14 on 2026-02-05 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def _safe_rename_index(apps, schema_editor, table_name, old_name, new_name):
    cursor = schema_editor.connection.cursor()
    cursor.execute(
        """
        SELECT COUNT(1) FROM information_schema.statistics
        WHERE table_schema = DATABASE()
          AND table_name = %s
          AND index_name = %s
        """,
        [table_name, old_name],
    )
    old_exists = cursor.fetchone()[0] > 0
    cursor.execute(
        """
        SELECT COUNT(1) FROM information_schema.statistics
        WHERE table_schema = DATABASE()
          AND table_name = %s
          AND index_name = %s
        """,
        [table_name, new_name],
    )
    new_exists = cursor.fetchone()[0] > 0
    if old_exists and not new_exists:
        schema_editor.execute(f"ALTER TABLE {table_name} RENAME INDEX {old_name} TO {new_name}")


def forwards(apps, schema_editor):
    _safe_rename_index(
        apps,
        schema_editor,
        "reminder_message",
        "reminder_recipient_is_read_idx",
        "reminder_me_recipie_7807e6_idx",
    )
    _safe_rename_index(
        apps,
        schema_editor,
        "reminder_message",
        "reminder_type_is_read_idx",
        "reminder_me_reminde_c80c5c_idx",
    )
    _safe_rename_index(
        apps,
        schema_editor,
        "reminder_message",
        "reminder_create_dt_idx",
        "reminder_me_create__3e06ae_idx",
    )


def backwards(apps, schema_editor):
    _safe_rename_index(
        apps,
        schema_editor,
        "reminder_message",
        "reminder_me_recipie_7807e6_idx",
        "reminder_recipient_is_read_idx",
    )
    _safe_rename_index(
        apps,
        schema_editor,
        "reminder_message",
        "reminder_me_reminde_c80c5c_idx",
        "reminder_type_is_read_idx",
    )
    _safe_rename_index(
        apps,
        schema_editor,
        "reminder_message",
        "reminder_me_create__3e06ae_idx",
        "reminder_create_dt_idx",
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customer_management", "0017_add_customer_handlers"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="remindermessage",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="接收提醒的用户（总所账号）",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_reminders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="接收人",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="other_type_content",
            field=models.CharField(
                blank=True,
                help_text="当日程类型为'其他'时，填写具体类型内容",
                max_length=200,
                null=True,
                verbose_name="其他类型内容",
            ),
        ),
    ]
