# Generated by Codex to align ReminderMessage index names with existing DB

from django.db import migrations


def _safe_rename_index(schema_editor, table_name, old_name, new_name):
    cursor = schema_editor.connection.cursor()
    cursor.execute(
        """
        SELECT COUNT(1) FROM information_schema.statistics
        WHERE table_schema = DATABASE()
          AND table_name = %s
          AND index_name = %s
        """,
        [table_name, old_name],
    )
    old_exists = cursor.fetchone()[0] > 0
    cursor.execute(
        """
        SELECT COUNT(1) FROM information_schema.statistics
        WHERE table_schema = DATABASE()
          AND table_name = %s
          AND index_name = %s
        """,
        [table_name, new_name],
    )
    new_exists = cursor.fetchone()[0] > 0
    if old_exists and not new_exists:
        schema_editor.execute(f"ALTER TABLE {table_name} RENAME INDEX {old_name} TO {new_name}")


def forwards(apps, schema_editor):
    _safe_rename_index(schema_editor, "reminder_message", "reminder_recipient_is_read_idx", "reminder_me_recipie_7807e6_idx")
    _safe_rename_index(schema_editor, "reminder_message", "reminder_type_is_read_idx", "reminder_me_reminde_c80c5c_idx")
    _safe_rename_index(schema_editor, "reminder_message", "reminder_create_dt_idx", "reminder_me_create__3e06ae_idx")


def backwards(apps, schema_editor):
    _safe_rename_index(schema_editor, "reminder_message", "reminder_me_recipie_7807e6_idx", "reminder_recipient_is_read_idx")
    _safe_rename_index(schema_editor, "reminder_message", "reminder_me_reminde_c80c5c_idx", "reminder_type_is_read_idx")
    _safe_rename_index(schema_editor, "reminder_message", "reminder_me_create__3e06ae_idx", "reminder_create_dt_idx")


class Migration(migrations.Migration):

    dependencies = [
        ("customer_management", "0018_rename_reminder_recipient_is_read_idx_reminder_me_recipie_7807e6_idx_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(forwards, backwards)],
            state_operations=[
                migrations.RenameIndex(
                    model_name="remindermessage",
                    old_name="reminder_recipient_is_read_idx",
                    new_name="reminder_me_recipie_7807e6_idx",
                ),
                migrations.RenameIndex(
                    model_name="remindermessage",
                    old_name="reminder_type_is_read_idx",
                    new_name="reminder_me_reminde_c80c5c_idx",
                ),
                migrations.RenameIndex(
                    model_name="remindermessage",
                    old_name="reminder_create_dt_idx",
                    new_name="reminder_me_create__3e06ae_idx",
                ),
            ],
        )
    ]
